imports:
  - /home/martinsa/labgrid/labgrid/driver/goshdriver.py
targets:
  main:
    resources:
      USBSerialPort:
        match:
          'ID_SERIAL_SHORT': 'FT0H9ZO2'
        speed: 500000
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver:
        txdelay: 0.005
      #GoshDriver: {}
